### ISSUE TITLE
TypeError: reduce() of empty sequence with no initial value

### ISSUE THREAD

**Issue by Swanson-Hysell** [Swanson-Hysell-Group/SAM_Header#1]
Hey Kevin,

I keep getting this error when running the main script on the T8-.csv which I made using the template.

```
$ python mk_sam_file.py T8-.csv 
Traceback (most recent call last):
  File "mk_sam_file.py", line 219, in <module>
    main()
  File "mk_sam_file.py", line 34, in main
    directory = reduce(lambda x,y: x+'/'+y, [sub for sub in file_name.split('/') if not sub.endswith('.csv')]) + '/'
TypeError: reduce() of empty sequence with no initial value
```

Thoughts?

**Comment by Swanson-Hysell** [comment]
T8-.csv is now in the repo.
